### ISSUE TITLE
"cursor mode" when using a controller is broken whilst Toolbox is running

### ISSUE THREAD

**Issue by qjv** [gwdevhub/GWToolboxpp#1522]
Upon injection, I get these:
1. R1 and L1 are weird and don't target as they should
2. Left analogical doesn't behave as intended, going to screen corners instead of being a cursor

When closing toolbox, it immediately goes back to normal

https://www.youtube.com/watch?v=l2yt1Vw1moQ

**Comment by 3vcloud** [comment]
I had issues when camera smoothing was enabled, does it work ok if you turn that off in toolbox game settings?

**Comment by 3vcloud** [comment]
Fixed for next version

**Comment by Michael-R-R** [comment]
Yeah it seems like a stubborn issue. :/

**Comment by Michael-R-R** [comment]
Also tested launching through Steam and using their controller support with DS4 closed. Same issue persists.

**Comment by nokiomanz** [comment]
I just updated to 8.4 and I still have the same issue on my side.

**Comment by pixel5015** [comment]
Good day, Just wanted to enquire of there has been an update to this or if I'm having an isolated problem. I am on 8.6 and with a Vader 4 pro(xbox style controller) I'm still having the problem of the cursor just jumping to the corners of the screen. 

Thank you very much.
